package ali

var ModelList = []string{
	"qwen-turbo", "qwen-plus", "qwen-max", "qwen-max-longcontext",
	"text-embedding-v1",
	"ali-stable-diffusion-xl", "ali-stable-diffusion-v1.5", "wanx-v1",

	"sambert-zhichu-v1",
	"sambert-zhiwei-v1",
	"sambert-zhixiang-v1",
	"sambert-zhide-v1",
	"sambert-zhijia-v1",
	"sambert-zhinan-v1",
	"sambert-zhiqi-v1",
	"sambert-zhiqian-v1",
	"sambert-zhiru-v1",
	"sambert-zhimiao-emo-v1",
	"sambert-zhida-v1",
	"sambert-zhifei-v1",
	"sambert-zhigui-v1",
	"sambert-zhihao-v1",
	"sambert-zhijing-v1",
	"sambert-zhilun-v1",
	"sambert-zhimao-v1",
	"sambert-zhiming-v1",
	"sambert-zhimo-v1",
	"sambert-zhina-v1",
	"sambert-zhishu-v1",
	"sambert-zhishuo-v1",
	"sambert-zhistella-v1",
	"sambert-zhiting-v1",
	"sambert-zhixiao-v1",
	"sambert-zhiya-v1",
	"sambert-zhiye-v1",
	"sambert-zhiying-v1",
	"sambert-zhiyuan-v1",
	"sambert-zhiyue-v1",
	"sambert-camila-v1",
	"sambert-perla-v1",
	"sambert-indah-v1",
	"sambert-clara-v1",
	"sambert-hanna-v1",
	"sambert-beth-v1",
	"sambert-betty-v1",
	"sambert-cally-v1",
	"sambert-cindy-v1",
	"sambert-eva-v1",
	"sambert-donna-v1",
	"sambert-brian-v1",
	"sambert-waan-v1",
}
